PB-00 fix(deps): update dependencies and workflows

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,10 @@ jobs:
       run: npm_config_yes=true npx lockfile-lint --path package-lock.json --allowed-hosts npm --validate-https
 
     - name: build typescript
-      run: npm run build -- --noEmit
+      run: npm run build
+
+    - name: package node_modules
+      run: npm run package
 
     - name: run tests and instrument coverage
       run: npm run coverage
@@ -38,7 +41,7 @@ jobs:
       # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
       run: |
         git diff --exit-code --stat -- . ':!node_modules' \
-        || (echo "##[error] found changed files after build. please 'npm run build'" \
+        || (echo "##[error] found changed files after build. please 'npm run build && npm run package'" \
                  "and check in all changes" \
             && exit 1)
 
